apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-app
  template:
    metadata:
      labels:
        app: employee-app
    spec:
      containers:
        - name: employee-app
          image: employee-crud-docker-app:latest
          imagePullPolicy: Never

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/employees
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: mysql-password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
          ports:
            - containerPort: 8080