name: Java and docker test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-and-build:
    runs-on: ubuntu-latest


    steps:
      #Step-1 : Pull the code from your repository onto the Ubuntu runner
      - name: Checkout Code
        uses: actions/checkout@v4

      #Step-2 : #Step-1 : Pull the code from your repository onto the Ubuntu runner
      - name: Set up Jdk 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      #Step-3 : Running the container(App + <MySql)/verifies if docker compose is okay
      - name: Start container
        run: docker compose up -d --build

      #Step-4: Waiting for environment to get ready
      - name: Wait for environment
        run: sleep 120

      #Step-5: Run Junit and Mock tests
      - name: Run Integration test
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3307/employeecruddb
          SPRING_DATASOURCE_USERNAME: user123
          SPRING_DATASOURCE_PASSWORD: user123
          SPRING_JPA_HIBERNATE_DDL_AUTO: update
        run: mvn clean test

      #Step-6: Checking container status
      - name: Varify container health
        run: docker ps

      #step-7: Cleanup
      - name: Stop Environment
        if: always()
        run: docker-compose down














